version: '3.8'

services:
  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  express-app:
    build: .
    ports:
      - "3000:3000"
    environment:
      DB_HOST: mongo
      DB_USER: root
      DB_PASSWORD: example
      DB_NAME: ${DB_NAME}
      DB_PORT: 27017
      PORT: 3000
      ACCESS_KEY: ${ACCESS_KEY}
      SECRET_KEY: ${SECRET_KEY}
      AWS_BUCKET: ${AWS_BUCKET}
      REGION: ${REGION}
      MAIL_USERNAME: ${MAIL_USERNAME}
      MAIL_PASSWORD: ${MAIL_PASSWORD}
      NODE_ENV: ${NODE_ENV}
      JWT_SECRET: ${JWT_SECERT}
    depends_on:
      - mongo
    volumes:
      - .:/home/node/app 

  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8080:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongo
